# Generated by Django 5.1.2 on 2024-11-04 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjTraders', '0004_product_archived_date_product_last_activity_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='archived_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_activity_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should not contain numbers.', regex='^[^\\d]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='This field should not contain numbers.', regex='^[^\\d]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field should not contain numbers.', regex='^[^\\d]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='This field should not contain numbers.', regex='^[^\\d]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15),
        ),
    ]
