# Generated by Django 5.1.2 on 2024-11-05 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjTraders', '0005_remove_product_archived_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Address must be at least 3 characters long.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='This field should not contain numbers.', regex='^[^\\d]+$')]),
        ),
    ]
